<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_tags
 *
 * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::_('behavior.core');
JHtml::_('formbehavior.chosen', 'select');

// Get the user object.
$user = JFactory::getUser();

// Check if user is allowed to add/edit based on tags permissions.
// Do we really have to make it so people can see unpublished tags???
$canEdit      = $user->authorise('core.edit', 'com_tags');
$canCreate    = $user->authorise('core.create', 'com_tags');
$canEditState = $user->authorise('core.edit.state', 'com_tags');

JFactory::getDocument()->addScriptDeclaration("
		var resetFilter = function() {
		document.getElementById('filter-search').value = '';
	}
");
//Prérequis :
// Renseigner le nombre de colonnes
$nbCol = 3;
// Configurer l'affichage des tags dans l'administration
// -> Système -> Configuration -> Tags -> Éléments taggés -> Image d'éléments : Afficher
// -> Système -> Configuration -> Tags -> Éléments taggés -> Description de l'élément : Afficher
// -> Système -> Configuration -> Tags -> Éléments taggés -> Renseigner le Nombre maximal de caractères

$itemcount = count($this->items);
$counter = 0;
?>
<form action="<?php echo htmlspecialchars(JUri::getInstance()->toString()); ?>" method="post" name="adminForm" id="adminForm" class="form-inline">
	<?php if ($this->params->get('show_headings') || $this->params->get('filter_field') || $this->params->get('show_pagination_limit')) : ?>
		<fieldset class="filters btn-toolbar">
			<?php if ($this->params->get('filter_field')) : ?>
				<div class="btn-group">
					<label class="filter-search-lbl element-invisible" for="filter-search">
						<?php echo JText::_('COM_TAGS_TITLE_FILTER_LABEL') . '&#160;'; ?>
					</label>
					<input type="text" name="filter-search" id="filter-search" value="<?php echo $this->escape($this->state->get('list.filter')); ?>" class="inputbox" onchange="document.adminForm.submit();" title="<?php echo JText::_('COM_TAGS_FILTER_SEARCH_DESC'); ?>" placeholder="<?php echo JText::_('COM_TAGS_TITLE_FILTER_LABEL'); ?>" />
					<button type="button" name="filter-search-button" title="<?php echo JText::_('JSEARCH_FILTER_SUBMIT'); ?>" onclick="document.adminForm.submit();" class="btn">
						<span class="icon-search"></span>
					</button>
					<button type="reset" name="filter-clear-button" title="<?php echo JText::_('JSEARCH_FILTER_CLEAR'); ?>" class="btn" onclick="resetFilter(); document.adminForm.submit();">
						<span class="icon-remove"></span>
					</button>
				</div>
			<?php endif; ?>
			<?php if ($this->params->get('show_pagination_limit')) : ?>
				<div class="btn-group pull-right">
					<label for="limit" class="element-invisible">
						<?php echo JText::_('JGLOBAL_DISPLAY_NUM'); ?>
					</label>
					<?php echo $this->pagination->getLimitBox(); ?>
				</div>
			<?php endif; ?>
			<input type="hidden" name="filter_order" value="" />
			<input type="hidden" name="filter_order_Dir" value="" />
			<input type="hidden" name="limitstart" value="" />
			<input type="hidden" name="task" value="" />
			<div class="clearfix"></div>
		</fieldset>
	<?php endif; ?>
	<?php if (empty($this->items)) : ?>
		<p><?php echo JText::_('COM_TAGS_NO_ITEMS'); ?></p>
	<?php else : ?>
		<?php // Début de l'affichage des articles ?>
		<div class="tags">
            <?php foreach ($this->items as $key => &$item) : ?>
                <?php $rowcount = ((int) $key % (int) $nbCol) + 1; ?>
                <?php if ($rowcount === 1) : ?>
                    <?php $row = $counter / $nbCol; ?>
                    <div class="items-row cols-<?php echo (int) $nbCol; ?> <?php echo 'row-' . $row; ?> row-fluid clearfix">
                <?php endif; ?>
                <div class="col-sm-<?php echo round(12 / $nbCol); ?>">
					<?php // Début de l'article ?>
                    <div class="item column-<?php echo $rowcount; ?><?php echo $item->core_state == 0 ? ' system-unpublished' : null; ?> " itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
						<?php // Affichage du titre ?>
                        <div class="page-header">
                            <h2 itemprop="name">
                                <a href="<?php echo JRoute::_($item->link); ?>" itemprop="url">
                                	<?php echo $this->escape($item->core_title); ?>
                                </a>
                            </h2>
                        </div>
						<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
						<?php echo $item->event->afterDisplayTitle; ?>
						<?php // Affichage de l'image d'intro si elle existe ?>
                  		<?php $images = json_decode($item->core_images); ?>
        				<?php if ($this->params->get('tag_list_show_item_image', 1) == 1) : ?> 
							<?php 
								$img_intro = ''; //Valeur par défaut
								//Récup l'image de l'article
								if (isset($images->image_intro) && !empty($images->image_intro))
									$img_intro = $images->image_intro;
								//Récup l'image d'un évènement
								if (isset($images->header) && !empty($images->header))
									$img_intro = $images->header;
							?>
							<?php if(!empty($img_intro)) : ?>
                        	<?php $imgfloat = empty($images->float_intro) ? 'none' : $images->float_intro; ?>
                        	<div class="pull-<?php echo htmlspecialchars($imgfloat, ENT_COMPAT, 'UTF-8'); ?> item-image">
                              <a href="<?php echo JRoute::_($item->link); ?>">
                                  <img
                                  <?php if (isset($images->image_intro_caption) && !empty($images->image_intro_caption)) : ?>
                                    <?php echo 'class="caption"' . ' title="' . htmlspecialchars($images->image_intro_caption) . '"'; ?>
                                  <?php endif; ?>
                                      src="<?php echo htmlspecialchars($img_intro, ENT_COMPAT, 'UTF-8'); ?>"
                                      itemprop="thumbnailUrl"/>
                              </a>
                            </div>
							<?php endif; ?>
                        <?php endif; ?>
						<?php if ($this->params->get('tag_list_show_item_description', 1)) : ?>
							<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
							<?php echo $item->event->beforeDisplayContent; ?>
							<?php // Affichage du texte ?>
							<div class="item-introtext">
								<?php echo JHtml::_('string.truncate', $item->core_body, $this->params->get('tag_list_item_maximum_characters')); ?>
							</div>
							<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
							<?php echo $item->event->afterDisplayContent; ?>
						<?php endif; ?>
						<?php // Affichage du lire la suite s'il a été configuré dans l'article'?>
                       	<?php if(!empty($item->core_params->get('alternative_readmore'))) : ?>
                        <p class="readmore">
                            <a class="btn" href="<?php echo $item->link; ?>" itemprop="url" aria-label="<?php echo $this->escape($item->core_title); ?>">
                              <span class="icon-chevron-right" aria-hidden="true"></span> 
                              <?php echo $item->core_params->get('alternative_readmore'); ?>
                            </a>
						</p>
                        <?php endif; ?>
                        <div class="clearfix"></div>
                    </div>
                    <!-- end item -->
                    <?php $counter++; ?>
                </div><!-- end span -->
                <?php if (($rowcount == $nbCol) or ($counter == $itemcount)) : ?>
                    </div><!-- end row -->
                <?php endif; ?>
            <?php endforeach; ?>
		</div>
	<?php endif; ?>
</form>
